'-----------------------------------
' SysML basic concepts illustrated
' JMB 2017
'-----------------------------------
@startuml
' File where const and functions are defined:
!include Defs.txt
'-----------------------------------

:Etat;
if () then (yes)
  :EtatYes;
else (no)
  :EtatNo;

@enduml
