'-----------------------------------
' SysML basic concepts illustrated
' JMB 2019
'-----------------------------------
@startuml
' File where const and functions are defined:
!include Defs.txt
'-----------------------------------

class Req REQ
class SubReq REQ
Req +- SubReq
@enduml
