
[appendix]
[[acro]]
== Acronymes
Liste (non exhaustive) des acronymes utilisés dans ce livre :

[horizontal]
ACT::
_**ACT**ivity Diagram_, le diagramme d'activité  (cf. <<act>>)

BDD::
_**B**lock **D**efinition **D**iagram_, le diagramme de définition de blocs (cf. <<bdd>>)

CESAM::
_**CES**AMES **A**rchitecture **M**ethod_, le _framework_ d'architecture et de modélisation de {CESAMES} (cf. <<cesamOverview>>)

DS::
**D**iagramme de **S**équence (cf. <<seq>>)

DSS::
**D**iagramme de **S**équence **S**ystème (cf. <<seq>>)

fUML::
//_**f**oundational **UML**_, a subset of the standard Unified Modeling Language (UML) for which there are standard, precise execution semantics.
_**f**oundational **UML**_, un sous-ensemble du standard {uml} pour lequel il existe une
sémantique d'exécution standard et précise

IBD::
_**I**nternal **B**lock **D**iagram_, le diagramme de blocs internes  (cf. <<ibd>>)

IDE::
_**I**ntegrated **D**evelopment **E**nvironment_, environnement de développement intégré
(comme {eclipse} ou {intelliJ})

IS::
**I**ngénierie **S**ystème

[[MBSE]] MBSE::
_**M**odel-**B**ased **S**ystems **E**ngineering_, Ingénierie systèmes basée modèles

OOSEM:: 
_**O**bject-**O**riented **S**ystems **E**ngineering **M**ethod_)

PAR::
_**Par**ametric Diagram_, le diagramme paramétrique (cf. <<param>>)

PKG::
_**P**ac**k**a**g**e Diagram_, le diagramme des paquetages (cf. <<package>>)

REQ::
_**REQ**uirements Diagram_, le diagramme des exigences (cf. <<reqs>>)

SD::
_**S**equence **D**iagram_, le diagramme de séquences (cf. <<seq>>)

STM::
_**ST**ate **M**achine Diagram_, le diagramme d'états (cf. <<stm>>)

SysML(R)::
_**Sys**tems **M**odeling **L**anguage_

UC::
_**U**se **C**ase Diagram_, le diagramme des cas d'utilisation (cf. <<uc>>)

UML(R)::
_**U**nified **M**odeling **L**anguage_

[appendix]
[[traductions]]
== Traductions

//-----------------------------------------------
ifndef::final[]
.Commentaire
[CAUTION]
====
*****
Peut-être à merger avec l'index... Mais utile pour l'instant pour se mettre d'accord sur les termes français.
*****
====
//-----------------------------------------------
endif::final[]

De nombreux utilisateur de {sysml} sont habitués aux termes anglais de
cette notation.
Idem pour les utilisateurs de {CESAM}.
Nous reprenons ici la liste des traductions françaises que nous avons utilisées
(et qui ne sont pas nécessairement standards) pour permettre au lecteur de faire une correspondance.

[horizontal]
_Activity Diagram_:: Diagramme d'activité  (cf. <<act>>)
_Actor_:: Acteur
_Block Definition Diagram_:: Diagramme de définition de blocs (cf. <<bdd>>)
_Constructional flows or objects_:: 	Flux ou objets organiques
_Constructional requirements_:: 	Exigences organiques
_Constructional scenarios_:: 	Scénarios organiques
_Constructional vision_:: 	Vision organique
_Components_::	Composants
_Composite State_:: État composite (ou super-état)
_Diagram Frame_ (et _Header_):: Cadre (et cartouche) (cf. <<cadre>>)
_Dynamics_:: 	Comportement
_Environment Architecture_::	Contexte
_Expected properties_::	Propriétés attendues
_Flows_:: 	Flux
_Functional flows or objects_:: 	Flux ou objets fonctionnels
_Functional modes_:: 	Modes fonctionnels
_Functional requirements_:: 	Exigences fonctionnelles
_Functional scenarios_:: 	Scénarios fonctionnels
_Functional vision_:: 	Vision fonctionnelle
_Functions_::	Fonctions
_Internal Block Diagram_:: Diagramme de blocs internes  (cf. <<ibd>>)
_Missions_::	Missions
_Multiplicity_:: Cardinalité (ou Multiplicité)
_Needs_:: 	Besoins
_Operational contexts_:: 	Contextes opérationnels (cf. <<visionOpState>>)
_Operational vision_:: 	Vision opérationnelle  (cf. <<visionOp>>)
_Operational flows or objects_:: 	Flux ou objets opérationnels (cf. <<visionOpFlow>>)
_Operational scenarios_:: 	Scénarios opérationnels (cf. <<visionOpDyn>>)
_Parametric Diagram_:: Diagramme paramétrique (cf. <<param>>)
_Package_:: Paquetages, mais nous préférons garder Package, admis dans le vocabulaire courant,
du moins en informatique.
_Package Diagram_:: Diagramme des paquetages (cf. <<package>>)
_Requirements_:: Exigences
_Requirements Diagram_:: Diagramme des exigences (cf. <<reqs>>)
_Sequence Diagram_:: Diagramme de séquences (cf. <<seq>>)
_Stakeholders_:: Parties prenantes (du système)
_States_:: 	États
_State Machine_:: Machine à état
_State Machine Diagram_:: Diagramme d'états (cf. <<stm>>)
_Static elements_:: 	Structure
_Use Case Diagram_:: Diagramme des cas d'utilisation (cf. <<uc>>)

[appendix]
include::notations.adoc[leveloffset=+1]

[appendix]
[[histoire]]
== Les histoires de SysML et de Papyrus

=== Histoire de SysML

{SysML} est né...
Après la définition, à la fin des années 90, du formalisme de modélisation unifié {UML},
l'{INCOSE} a décidé en 2003 de faire d'{UML} ce langage commun pour l'IS.
{UML} contenait en effet déjà à l'époque nombre de diagrammes indispensables,
comme les diagrammes de séquence, d'états, de cas d'utilisation, etc.
Le travail sur la nouvelle version UML 2.0, entamé à l'{OMG} à peu près à la
même période, a abouti à la définition d'un langage de modélisation très proche
du besoin des ingénieurs système, avec des améliorations notables sur les
diagrammes d'activité et de séquence, ainsi que la mise au point du diagramme de
structure composite.
Cependant, il restait une barrière psychologique importante à l'adoption d'UML
par la communauté de l'IS : sa teinture "logicielle" !
La possibilité d'extension d'{UML}, grâce au concept de stéréotype, a permis
d'adapter le vocabulaire pour les ingénieurs système.
En éliminant les mots "objet" et "classe" au profit du terme plus neutre "bloc",
c'est-à-dire en gommant les aspects les plus informatiques d'{UML}, et en
renommant ce langage de modélisation, l'{OMG} veut promouvoir {SysML} comme un
nouveau langage différent d'{UML}, tout en profitant de sa filiation directe.
L'{OMG} a annoncé l'adoption de {SysML} en juillet 2006 et la disponibilité de
la première version officielle (SysML v1.0) en septembre 2007.
Une nouvelle spécification SysML v1.1 a été rendue publique en décembre 2008,
puis la v1.2 en juin 2010,
la v1.3 en juin 2012,
la v1.4 en septembre 2015,
et la révision courante {SysML} v1.5 a été publiée en mai 2017.

//........
//=> Diagrammes et jalons importants
//........

........
=> Le futur et les changements techniques à venir, dans les cartons de l'omg.
........

=== Histoire de Papyrus

{Papyrus} est né...

[appendix]
== Couverture des concepts

Comme indiqué en avant-propos de ce livre, nous n'abordons qu'une partie des concepts {sysml}, les plus importants.
Nous nous sommes basés sur la classification du système de certification de l'{omg} <<OCSMP>>.

Nous indiquons dans le tableau ci-dessous le différents concepts du niveau initial (_{ModelUser}_) de la certification _Certified Systems Modeling Professional_(TM) (c'est pour cela qu'ils sont listés ici en anglais) et où ils sont abordés dans le livre.


//Pour enlever le mot "Chapitre" des références dans le tableau
:old-chapter-refsig: {chapter-refsig}
:!chapter-refsig:
:old-section-refsig: {section-refsig}
:!section-refsig:

=== Modèles d'exigences

[align="center",cols="3,1*^",options="header",width=100]
|======================
|	Concept         |   Lien
| Requirements       |		<<reqs-init>>, <<reqs>>
| deriveRqt, verify, satisfy, refine, trace, containment | <<reqLinks>>
| Requirements Diagram | <<reqs-init>>, <<reqDiags>>
| Use Case Diagram | <<uc-init>>, <<ucDiags>>, <<uc>>
| use case, actor, and subject | <<uc>>
| association, include, extend, generalization | <<uc>>
|======================

=== Modèles structurels

[align="center",cols="3,1*^",options="header",width=100]
|======================
|	Concept         |   Lien
| Package Diagram       | <<pkg-init>>, <<package>>
| ownership, namespace, containment | <<namespace>>
| dependency | <<pkg-dep>>
| view, viewpoint | <<pkg-types>>
| Block definition, Block usage |
| valuetype (with units) |
| value properties, parts, references, and operations |
| Block Definition Diagram |
| compartments |
| specialization, associations (including compositefootnote:[but not shared aggregation]), multiplicities|
| Internal Block Diagram |
| enclosing block |
| flow ports and standard ports |
| connectors and item flows |
|  representation of parts |
| constraint blocks |
| Parametric Diagram |
|  constraint properties, constraint parameters, and constraint expressions |
| connecting constraint properties and value properties with binding connectors |
|======================

=== Modèles comportementaux

[align="center",cols="3,1*^",options="header",width=100]
|======================
|	Concept         |   Lien
| Activity Diagram |
| I/O flow including object flow, parameters and parameter nodes, and pins |
|  control flow including control nodes |
| activity partitions (swimlanes) |
| actions |
| send signal action |
| accept event action |
| Sequence Diagram|
| lifelines, asynchronous and synchronous messages |
| interaction references |
| State Machine Diagram |
| states and regions |
| transitions |
| trigger by time and signal events, guard, and action |
| behaviors (entry, exit, and do)|
|======================

=== Eléments transverses

[align="center",cols="3,1*^",options="header",width=100]
|======================
|	Concept         |   Lien
| Allocation | <<allocation>>
|  AllocatedFrom and AllocatedTo|
| representation (callouts, compartments, allocate activity partitions, and tables) |
| special notations for comment, rationale, problem, and constraint |
|  diagram frames, ports, parameters, and anchors on diagram frames |
| diagram header, and diagram description | <<cadre>>
| Stereotype |
|======================

//Pour remettre le mot "Chapitre" des références dans le tableau
:chapter-refsig: {old-chapter-refsig}
:section-refsig: {old-section-refsig}

[appendix]
[[sysml15]]
== Nouveautés de SysML {sysmlversionlast}

Pour les lecteurs habitués à {sysml} `1.4` nous résumons ici les principales nouveautés de la version `{sysmlversionlast}`.

=== Exigences

Nous avons traité en détail cet aspect dans la section <<req15>>.

=== Suite

http://model-based-systems-engineering.com/2017/05/17/whats-new-in-sysml-1-5-miscellaneous/

[appendix]
[[sysml2]]
== Et le futur? SysML 2!

Quelques mots en provenance de l'{omg}.

[appendix]
[[index]]
== Index (Reference guide)
Liste des concepts et renvoies vers leur description dans le livre.
