[[visionEnv]]
= Contexte du système

//-----------------------------------------------
ifndef::final[]
.Commentaire
[CAUTION]
====
*****
Avant les visions, question du contexte et du WHO.
*****
====
//-----------------------------------------------
endif::final[]

//---------------------------------------------------------------------------------
== Principes

Blabla sur cette partie en générale.

ifdef::backend-pdf[[align="center",cols="h,6*^",options="header"]]
ifndef::backend-pdf[[align="center",cols="h,6*^",options="header",width=100]]
|======================
|  | {Requirements} | {State}| {Structure} | {Behavior}	| {Flows} | {Crosscutting}
| {organisation} 6+|
| {context} 5+| {here} .4+<.>m|
| {analysis}	| | | | |  
| {design}	| | | | | 
| {implementation}	| | | | | 
|======================

== Mise en œuvre en SysML

.Concepts définis dans cette section
[NOTE,icon=sysml.jpeg]
=====
Nous aborderons dans cette partie les concepts du niveau
initial (_{ModelUser}_) de la certification _Certified Systems Modeling Professional_(TM):
use case diagram, actor, generalization, package,  block definition diagram, block, item flows, comment.
=====

//-----------------------------------------------
//-- Commentaire
//-----------------------------------------------
ifndef::final[]
.Commentaire
[CAUTION]
====
Vérifier les termes (absents ou en trop)!
====
endif::final[]
//-----------------------------------------------

Les acteurs sont bien connus de {sysml} / {uml}.
Nous allons donc utilise un diagramme des cas d'utilisation pour lister les parties prenantes et leur hiérarchie éventuelle.
Nous placerons ensuite dans un _Block Definition Diagrams_ le système (le {projectName} dans notre exemple) et ses interactions avec les parties prenantes.
Pour représenter les flux, {sysml} possède le concept d'_Item Flow_, qui correspond parfaitement à ce besoin.  

[[visionProjectStake]]
=== Diagramme des parties prenantes (_Stakeholder Hierarchy Diagram_)

[[visionProjectStakeFig]]
ifdef::FR[.Exemple de Diagramme des parties prenantes]
ifdef::UK[.Example of Stakeholder Hierarchy Diagram]
image::diagrams/SHS_stakeholder_hierarchy_diagram.SVG[width="80%",scaledwidth=80%]

TIP: Il existe un stéréotype {sysml} +<<Stakeholder>>+ qui peut être utilisé pour clairement accentuer le rôle de ces acteurs.

[[visionProjectEnv]]
=== Environment Diagram

[[visionProjectEnvFig]]
ifdef::FR[.Exemple de Diagramme d'environnement projet (tirée de <<CESAM17>>)]
ifdef::UK[.Example of Environment Diagram (taken from <<CESAM17>>)]
image::diagrams/SHS_environment_diagram.SVG[width="80%",scaledwidth=80%]

== {resume}

== {revisions}

. Quelles sont les différences entre *utilisateurs* et *parties prenantes* ?
. Pourquoi regrouper les parties prenantes en "en lien avec le Projet" ou "en lien avec le Produit" ?
. Quelle est la différence entre un _package_ de type *_model_* et un _package_ de type *_package_* ?
