[[AvantPropos]]
= Avant-propos

== Ce que *n'est pas* ce livre :

Ce livre *n'est pas* un livre :

- de référence (pour cela, même s'il est en anglais, nous conseillons <<Friedenthal2016>>)
- sur la meilleure approche méthodologique possible avec {sysml} (car il n'y en a pas d'absolue)
- pour réviser l'examen de certification de l'{OMG} ou de l'{incose}, comme <<OCSMP>>
 (mieux vaut vous plonger dans la spécification de référence <<SysML>>)

== Pourquoi lire ce livre ?

Il peut y avoir plusieurs raisons pour lire ce livre, même partiellement.
Voici les différentes raisons qui peuvent vous y avoir amené :

Je veux fiabiliser mon processus d'{IS}::
Vous êtes un professionnel, dans le domaine de l'{is}, et vous êtes intéressé par la modélisation.
Nous espérons que les conseils pratiques, appliqués et appuyés sur l'outil {papyrus},
vous permettront de tester l'intérêt de {sysml} pour votre domaine.

Je veux apprendre {SysML} par la pratique::
Ce livre est entièrement réalisé dans cet objectif : apprendre les concepts et la notation en les mettant en oeuvre.
Nous allons à l'essentiel des concepts et surtout nous vous permettons de les
manipuler de manière concrète dans l'outil {papyrus}.

Je veux maîtriser {Papyrus}::
Le logiciel prend une part de plus en plus importante dans le développement de systèmes complexes.
Si vous utilisez déjà Papyrus comme modeleur {uml}, et que vous souhaitiez apprendre {sysml} en conservant vos habitudes,
ce livre, réalisé en collaboration avec l'équipe du {list} en charge du développement de {papyrus}, devrait vous y aider.

Je veux utiliser des solutions _open-source_ pour l'{IS}::
C'est un des avantages de {papyrus} : c'est un logiciel ouvert, auxquels de nombreux programmeurs contribuent,
permettant ainsi la prise en compte rapide des remarques utilisateurs, la disponibilité d'un forum riche, etc.

Je veux utiliser des normes d'{IS}::
Si, comme généralement en {is}, vous basez vos processus et outils sur des standards, vous aurez
avec {sysml}, une notation standard pour vos modèles (apprise en filière technologique STI-2D des Lycées,
en classes préparatoires et dans beaucoup d'écoles d'ingénieurs).
Et vous aurez, avec {papyrus}, un outils 100% conforme à la spécification.

Je veux gagner du temps::
Nous avons essayer de concevoir ce livre comme un manuelfootnote:[Au sens latin du terme : "que l'on peut
avoir toujours à portée de main".], outil et pratique, en travaillant l'organisation des concepts
et des pratiques.

== À qui s'adresse le livre ?

En fonction de votre profil, vous pourrez avoir une lecture plus ou moins complète de cet ouvrage.
Loin de nous l'idée de forcer la façon d'en aborder les chapitres, nous vous recommandons néanmoins
les pistes de lectures suivantes selon la situation :

.Conseils de lecture en fonction de votre niveau en SysML (en ligne) et en Papyrus (en colonne)
[align="center",cols="h,3*^",options="header",width=100]
|======================
|	{sysml}{nbsp}{nbsp}{nbsp}/{nbsp}{nbsp}{nbsp}{papyrus}| Découverte              | Initié               | Professionnel
| Découverte	     | <<Intro,1>>,<<etudeCas,2>>,<<install,3>>,<<overview,4>> | <<Intro,1>>,<<etudeCas,2>>,(<<install,3>>),<<overview,4>> | <<Intro,1>>,<<etudeCas,2>>,<<overview,4>>
| Initié			     | (<<Intro,1>>),<<etudeCas,2>>,<<install,3>>,(<<overview,4>>),<<RE,5>>,<<usages,6>>,<<archi,7>>,<<behavour,8>>,<<interaction,9>>	| (<<Intro,1>>),<<etudeCas,2>>,(<<install,3>>,<<overview,4>>),<<RE,5>>,<<usages,6>>,<<archi,7>>,<<behavour,8>>,<<interaction,9>>	| (<<Intro,1>>),<<etudeCas,2>>,(<<overview,4>>),<<RE,5>>,<<usages,6>>,<<archi,7>>,<<behavour,8>>,<<interaction,9>>
| Professionnel		 |(<<Intro,1>>),<<etudeCas,2>>,<<install,3>>,(<<RE,5>>,<<usages,6>>,<<archi,7>>,<<behavour,8>>,<<interaction,9>>),<<crossCuting,10>>,<<realLife,11>> | (<<Intro,1>>),<<etudeCas,2>>,(<<install,3>>,<<RE,5>>,<<usages,6>>,<<archi,7>>,<<behavour,8>>,<<interaction,9>>),<<crossCuting,10>>,<<realLife,11>> | (<<Intro,1>>),<<etudeCas,2>>,(<<overview,4>>),<<RE,5>>,<<usages,6>>,<<archi,7>>,<<behavour,8>>,<<interaction,9>>,<<crossCuting,10>>,<<realLife,11>>
|======================

Si vous êtes débutant en {IS}, nous vous conseillons en parallèle de vous initier.
Le livre n'aborde pas directement les concepts systèmes.

//== Comment lire ce livre ?

//-----------------------------------------------
ifndef::final[]
.Commentaire
[CAUTION]
====
*****
- Préciser ici que l'objectif du livre étant de fournir un support de formation à
SysML par la pratique, le chapitre "Bien démarrer" est primordiale.
- Ajouter des ordres de chapitres en fonction des publiques (étudiants, ingénieur, etc.)
*****
====
//-----------------------------------------------
endif::final[]

Ce document a été réalisé de manière à être lu de préférence
dans sa version électronique, ce qui permet de
naviguer entre les références et les renvois interactivement, de consulter
directement les documents référencés par une URL, etc.

[NOTE]
====
Si vous lisez la version papier de ce document, ces liens clickables ne
vous servent à rien, mais n'hésitez pas à en consulter la version {siteurl}[électronique]!
====

//== Comment se préparer à lire au mieux ce livre ?

//-----------------------------------------------
ifndef::final[]
.Commentaire
[CAUTION]
====
*****
=> Proposer des pistes  de « formation » pour rentrer dans le cadre le cas échéant.

=> Description de la mise en place de l’environnement pour la mise en pratique.

=> Fournir un petit outillage Papyrus dédié à la mise en pratique du livre (Spécialisation particulière, projet type, exemple de modèle, cheat sheet, etc.) que l'on pourrait mettre à disposition via le site de Papyrus www.eclipse.org/papyrus/
*****
====
//-----------------------------------------------
endif::final[]

[[niveauConcepts]]
.Niveaux de concepts SysML
[NOTE]
======
Les différents niveaux de concepts {SysML} que nous utilisons dans ce livre sont alignés sur
ceux du programme de certification de l'{OMG} <<OCSMP>>.
======

== Conventions typographiques et symboles récurrents

Nous avons utilisé un certain nombre de conventions personnelles pour rendre ce document le plus agréable à lire et le plus
utile possible, grâce notamment à la puissance d'{asciidoc} :

- des mises en formes particulières (e.g., `NomDeBloc` pour un élément de modèle),
- des références bibliographiques (comme la spécification <<SysML>>), présentées en fin de document (cf. <<refs>>),
- tous les flottants (figures, tableaux) sont listés à la suite de la table des matière, [red yellow-background]#XXX check this XXX#
- les termes anglais (souvent incontournables) sont repérés en _italique_, non pas pour indiquer qu'il s'agit d'un
mot anglais, mais pour indiquer au lecteur que nous employons volontairement ces termes (e.g., _Requirements_),
- un certain nombre de symboles viennent identifier les notes :

//-----------------------------------------------
ifndef::final[]
.Commentaire
[CAUTION]
====
*****
Ce symbole permet de repérer rapidements des commentaires pour nous-mêmes.
Il ne doit pas figurer dans la version finale en ligne, ni dans le PDF.
De même [red yellow-background]#XXX ces textes XXX# devraient être éliminés au fur et à mesure...

*****
====
//-----------------------------------------------
endif::final[]

NOTE: Ceci est une simple note, un point remarquable.

WARNING: Attention, piège ou erreur à éviter.

IMPORTANT: Ceci est un point important.

.Convention : Ceci est une convention ou une bonne pratique
[TIP]
====
Dans ces notes, nous distillerons des conseils, des bonnes pratiques ou des conventions que nous recommandons d'adopter.
====

.Définition : Exemple (OMG SysML v1.5, p. 152)
[NOTE,icon=sysml.jpeg]
====
Ces notes concernent des définitions tirées de la spécification {sysml} et sont donc précisément référencées.
====

== Historique

Ce document est la compilation de plusieurs années d'enseignement de {sysml}
ou de {papyrus} par les auteurs depuis plus de dix ans, que ce soit :

- au http://dep-informatique.univ-pau.fr/live/masterTI[Master TI], de l'{uppa} (avec {nico}),
- au http://spiderman-2.laas.fr/M2R-SAID/[Master Recherche SAID], de l'{UPS},
- au http://mathsinfo.univ-tlse2.fr/accueil/formations/master-ice/[Master ICE] de l'{ut2j} (avec {pdss}),
- au _Master of Science_ de Göteborg, Suède (introduction réalisée par {nico}),
- à {uag}, au Mexique (40h de formation professionnelle à des employés de Continental Mexique),
- [red yellow-background]#XXX to be completed by Seb XXX#
- ou plus récemment au {dl} de {ups} (avec {christelle}).

Vous trouverez en référence (cf. <<refs>>) les ouvrages et autres documents utilisés pour la réalisation de ce livre.

/////
== Remerciements

XXX Penser à remercier : {rf}, {pr}, {nico}, Nicolas Hili, ... XXX

/////

:icons: font
